version: "2"
services:
    elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:5.3.0"
        hostname: elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            ES_JAVA_OPTS: "-Xms1g -Xmx1g"
        restart: always
        networks:
            - elkpy_net
    logstash:
        build: ./logstash
        hostname: logstash
        ports:
            - "5005:5005"
            - "5006:5006"
        depends_on:
            - elasticsearch
        restart: always
        networks:
            - elkpy_net
    kibana:
        image: "docker.elastic.co/kibana/kibana:5.3.0"
        hostname: kibana
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        restart: always
        networks:
            - elkpy_net
networks:
  elkpy_net:
    driver: bridge